name: Build And Push
on:
  push:
    tags:
      - 'v*'
jobs:
  push-multiarch:
    name: Build and Push amd64 and arm64
    runs-on: ubuntu-latest
    env:
      TAG: ${{github.ref_name}}
      REPOSITORY_OWNER: ${{ github.repository_owner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{github.ref}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Registry Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set the GOLANG_VERSION value
        id: get-GOLANG_VERSION
        run: |
          echo "$(make -s log | grep GOLANG_VERSION)" >> "$GITHUB_ENV"

      - name: Build Container Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            "GOLANG_VERSION=${{env.GOLANG_VERSION}}"
          tags: ${{ env.REPOSITORY_OWNER }}/hardened-build-base:${{ env.TAG }}
          file: Dockerfile
          platforms: linux/amd64, linux/arm64

