name: Build And Push
on:
  push:
    tags:
      - 'v*'
jobs:
  linux-amd64:
    name: Build and Push linux amd64
    runs-on: ubuntu-latest
    env:
      TAG: ${GITHUB_REF_NAME}
      REPOSITORY_OWNER: ${{github.repository_owner}}
    steps:
      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{github.ref}}
      - name: build
        run: TAG=${TAG} ORG=${REPOSITORY_OWNER} make
      - name: push
        run: TAG=${TAG} ORG=${REPOSITORY_OWNER} make image-push

