name: Build And Push
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build
        run: TAG=${GITHUB_REF_NAME} make
      - name: push
        run: TAG=${GITHUB_REF_NAME} make image-push
  manifest:
    name: Docker manifest
    runs-on: ubuntu-latest
    steps:
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

