name: Build And Push
on:
  push:
    tags:
      - 'v*'
jobs:
  linux-amd64:
    name: Build and Push linux amd64
    runs-on: ubuntu-latest
    env:
      TAG: ${GITHUB_REF_NAME}
      REPOSITORY_OWNER: ${{github.repository_owner}}
    steps:
      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{github.ref}}
      - name: build
        run: TAG=${TAG} ORG=${REPOSITORY_OWNER} make
      - name: push
        run: TAG=${TAG} ORG=${REPOSITORY_OWNER} make image-push
  manifest:
    name: Docker manifest
    runs-on: ubuntu-latest
    needs: linux-amd64
    steps:
      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Create manifest
        run: |
          docker manifest create ${{github.repository_owner}}/hardened-build-base:${{github.ref_name}} \
            ${{github.repository_owner}}/hardened-build-base:${{github.ref_name}}-amd64
      - name: Push manifest
        run: docker manifest push ${{github.repository_owner}}/hardened-build-base:${{github.ref_name}}

